/** Offline brand-glyph resolution (simple-icons data merged module). */
import { test, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { siteGlyph } from '../src/client/site-icons.ts'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const source = readFileSync(join(root, 'src', 'client', 'site-icons.ts'), 'utf8')

const hit = (url: string) => {
  const g = siteGlyph(url)
  return g !== undefined ? g.c : undefined
}

test('site icons: v16 brand hosts resolve to brand colors', () => {
  expect(hit('https://github.com/org/repo')).toBe('#181717')
  expect(hit('https://gitlab.com/x')).toBe('#FC6D26')
  expect(hit('https://gitee.com/x')).toBe('#C71D23')
  expect(hit('https://hub.docker.com/team')).toBe('#2496ED')
  expect(hit('https://www.google.com/')).toBe('#4285F4')
  expect(hit('https://mail.google.com/')).toBe('#EA4335') // gmail, not google
})

test('site icons: v11 legacy brands (removed from newer simple-icons)', () => {
  expect(hit('https://console.aws.amazon.com/iam')).toBe('#232F3E')
  expect(hit('https://aws.amazon.com/')).toBe('#232F3E')
  expect(hit('https://portal.azure.com/')).toBe('#0078D4')
  expect(hit('https://dev.azure.com/org')).toBe('#0078D7')
  expect(hit('https://acme.slack.com/apps')).toBe('#4A154B') // subdomain suffix
  expect(hit('https://www.linkedin.com/in/me')).toBe('#0A66C2')
  expect(hit('https://dashboard.heroku.com/')).toBe('#430098')
})

test('site icons: atlassian workspace suffix and fallbacks', () => {
  expect(hit('https://myorg.atlassian.net/jira')).toBe('#0052CC')
  expect(hit('https://example.com/unknown')).toBeUndefined()
  expect(siteGlyph('not a url')).toBeUndefined()
  expect(siteGlyph(undefined, undefined)).toBeUndefined()
  expect(siteGlyph(undefined, 'github.com')?.c).toBe('#181717') // ssh host fallback
})

// ── the table's own integrity, which the colour assertions above cannot see ──
//
// The glyphs are 68 inlined SVG paths generated by `scripts/gen-site-icons.mjs`.
// A truncated path, a mistyped colour or a host alias pointing at a brand that
// was never added all render as a blank or partial square rather than as an
// error, so they are checked structurally here.

const glyphRows = source.split('const GLYPHS: Record<string, SiteGlyphData> = {')[1]!.split('\n}\n')[0]!
const hostRows = source.split('const HOST_SLUG: Record<string, string> = {')[1]!.split('\n}\n')[0]!

const glyphs = new Map<string, { path: string; color: string; raw: string }>()
for (const line of glyphRows.split('\n')) {
  if (line.trim().length === 0) continue
  const match = line.match(/^ {2}"([a-z0-9.-]+)": \{ p: "([^"]*)", c: (['"])(.*?)\3 \},$/)
  expect(match, `unparsable glyph row: ${line.slice(0, 80)}`).not.toBeNull()
  glyphs.set(match![1]!, { path: match![2]!, color: match![4]!, raw: line })
}

const hostSlugs = new Map<string, string>()
for (const line of hostRows.split('\n')) {
  if (line.trim().length === 0) continue
  const match = line.match(/^ {2}"([a-z0-9.-]+)": "([a-z0-9.-]+)",$/)
  expect(match, `unparsable host row: ${line.slice(0, 80)}`).not.toBeNull()
  hostSlugs.set(match![1]!, match![2]!)
}

test('site icons: the table parses and every brand is complete', () => {
  expect(glyphs.size).toBeGreaterThanOrEqual(60)
  for (const [slug, glyph] of glyphs) {
    // The floor is deliberately low: some marks are pure geometry (Vercel is a
    // 22-character triangle), while a truncated path is a handful of characters.
    expect(glyph.path.length, `${slug}: suspiciously short path`).toBeGreaterThan(15)
    expect(glyph.path.startsWith('M') || glyph.path.startsWith('m'), `${slug}: no leading move`).toBe(true)
    // Catches a merge artefact inside the path — a stray quote, a non-ASCII
    // character, an HTML entity — which would otherwise render as a squiggle.
    expect(glyph.path, `${slug}: illegal characters in path`).toMatch(/^[MmLlHhVvCcSsQqTtAaZz0-9eE.,\s+-]+$/)
    expect(glyph.color, `${slug}: colour must be #rrggbb`).toMatch(/^#[0-9A-Fa-f]{6}$/)
  }
})

test('site icons: the file is in the canonical form its generator writes', () => {
  // Six brands were once merged by hand with double-quoted colours, which is
  // exactly the drift that made the header's "machine generated" untrue.
  const handEdited = [...glyphs.values()].filter(glyph => glyph.raw.includes('c: "')).map(glyph => glyph.raw.slice(2, 40))
  expect(handEdited).toEqual([])
  expect(source).toMatch(/Generated by scripts\/gen-site-icons\.mjs/)
  expect(source).not.toMatch(/Keep the file machine-generated/)
})

test('site icons: no host alias points at a missing brand', () => {
  // A typo here silently drops that host's mark; the UI cannot distinguish
  // "this host has no glyph" from "the table is broken".
  const dangling = [...hostSlugs].filter(([, slug]) => !glyphs.has(slug))
  expect(dangling.map(([host, slug]) => `${host} -> ${slug}`)).toEqual([])
  expect(hostSlugs.size).toBeGreaterThanOrEqual(60)
})

test('site icons: aliases reach the specific brand, not the generic one', () => {
  expect(siteGlyph('https://gist.github.com/x')).toBe(siteGlyph('https://github.com/x'))
  expect(siteGlyph('https://registry.npmjs.org/x')).toBe(siteGlyph('https://npmjs.com/x'))
  // The cloud console is a Google Cloud entry, not a plain Google one.
  expect(siteGlyph('https://console.cloud.google.com/x')?.c).toBe('#4285F4')
  expect(siteGlyph('https://firebase.google.com/x')?.c).toBe('#4285F4')
})

test('site icons: a scheme-less URL resolves, and whitespace does not', () => {
  // The editor stores whatever the user typed, so `github.com` must work.
  expect(siteGlyph('github.com')).toBe(siteGlyph('https://github.com'))
  expect(siteGlyph('www.github.com')).toBe(siteGlyph('https://github.com'))
  expect(siteGlyph('   ')).toBeUndefined()
})
